// <auto-generated />
using System;
using Kiosk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kiosk.Infrastructure.Migrations.Sqlite
{
    [DbContext(typeof(KioskSqliteDbContext))]
    partial class KioskSqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Kiosk.Domain.Auditoria.AuditoriaEvento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor");

                    b.Property<int>("Canal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("canal");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("comercio_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("detalle_json");

                    b.Property<Guid?>("IntencionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("intencion_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_auditoria_eventos");

                    b.HasIndex("ComercioId");

                    b.ToTable("auditoria_eventos");
                });

            modelBuilder.Entity("Kiosk.Domain.Catalogos.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activa");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("comercio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("ComercioId", "Nombre")
                        .IsUnique();

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("Kiosk.Domain.Catalogos.Presentacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activa");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo_barras");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<int?>("PrecioCostoCentavos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("precio_costo_centavos");

                    b.Property<int>("PrecioVentaCentavos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("precio_venta_centavos");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("producto_id");

                    b.Property<int>("StockActual")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock_actual");

                    b.Property<int?>("StockMinimo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock_minimo");

                    b.HasKey("Id")
                        .HasName("pk_presentacion");

                    b.HasIndex("CodigoBarras");

                    b.HasIndex("ProductoId");

                    b.ToTable("presentacion");
                });

            modelBuilder.Entity("Kiosk.Domain.Catalogos.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("categoria_id");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("comercio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre_normalizado");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ComercioId", "NombreNormalizado");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("Kiosk.Domain.Comercios.Comercio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_comercios");

                    b.ToTable("comercios");
                });

            modelBuilder.Entity("Kiosk.Domain.Configuracion.Configuracion", b =>
                {
                    b.Property<Guid>("ComercioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("comercio_id");

                    b.Property<string>("Clave")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("clave");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("valor");

                    b.HasKey("ComercioId", "Clave")
                        .HasName("pk_configuraciones");

                    b.ToTable("configuraciones");
                });

            modelBuilder.Entity("Kiosk.Domain.Stock.MovimientoStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("motivo");

                    b.Property<int>("Origen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("origen");

                    b.Property<Guid>("PresentacionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("presentacion_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.Property<Guid?>("VentaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("venta_id");

                    b.HasKey("Id")
                        .HasName("pk_movimientos_stock");

                    b.HasIndex("VentaId");

                    b.HasIndex("PresentacionId", "CreatedAt");

                    b.ToTable("movimientos_stock");
                });

            modelBuilder.Entity("Kiosk.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("comercio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rol");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("ComercioId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Kiosk.Domain.Ventas.Caja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("comercio_id");

                    b.Property<int?>("DiferenciaCentavos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("diferencia_centavos");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_apertura");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_cierre");

                    b.Property<int?>("MontoDeclaradoCentavos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("monto_declarado_centavos");

                    b.Property<int?>("MontoEsperadoCentavos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("monto_esperado_centavos");

                    b.Property<int>("MontoInicialCentavos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("monto_inicial_centavos");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_cajas");

                    b.HasIndex("ComercioId")
                        .IsUnique()
                        .HasFilter("\"estado\" = 1");

                    b.HasIndex("UsuarioId");

                    b.ToTable("cajas");
                });

            modelBuilder.Entity("Kiosk.Domain.Ventas.LineaVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad");

                    b.Property<int>("PrecioUnitarioCentavos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("precio_unitario_centavos");

                    b.Property<Guid>("PresentacionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("presentacion_id");

                    b.Property<string>("PresentacionNombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("presentacion_nombre");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("producto_nombre");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("venta_id");

                    b.HasKey("Id")
                        .HasName("pk_linea_venta");

                    b.HasIndex("PresentacionId");

                    b.HasIndex("VentaId");

                    b.ToTable("linea_venta");
                });

            modelBuilder.Entity("Kiosk.Domain.Ventas.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Medio")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medio");

                    b.Property<int>("MontoCentavos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("monto_centavos");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("venta_id");

                    b.HasKey("Id")
                        .HasName("pk_pago");

                    b.HasIndex("VentaId");

                    b.ToTable("pago");
                });

            modelBuilder.Entity("Kiosk.Domain.Ventas.Venta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CajaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("caja_id");

                    b.Property<bool>("ClientGenerated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_generated");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("comercio_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero");

                    b.Property<int>("TotalCentavos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_centavos");

                    b.HasKey("Id")
                        .HasName("pk_ventas");

                    b.HasIndex("CajaId");

                    b.HasIndex("ComercioId", "Fecha");

                    b.ToTable("ventas");
                });

            modelBuilder.Entity("Kiosk.Domain.Whatsapp.Intencion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("comercio_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Decision")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("decision");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("ExpiraEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("expira_en");

                    b.Property<bool>("FueAudio")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fue_audio");

                    b.Property<string>("ResultadoJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("resultado_json");

                    b.Property<string>("StructuredCommandJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("structured_command_json");

                    b.Property<string>("TextoOriginal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("texto_original");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("WhatsappNumero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("whatsapp_numero");

                    b.HasKey("Id")
                        .HasName("pk_intenciones");

                    b.HasIndex("ComercioId");

                    b.HasIndex("WhatsappNumero", "Estado");

                    b.ToTable("intenciones");
                });

            modelBuilder.Entity("Kiosk.Domain.Whatsapp.WhatsappWhitelist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("comercio_id");

                    b.Property<string>("WhatsappNumero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("whatsapp_numero");

                    b.HasKey("Id")
                        .HasName("pk_whatsapp_whitelist");

                    b.HasIndex("ComercioId", "WhatsappNumero")
                        .IsUnique();

                    b.ToTable("whatsapp_whitelist");
                });

            modelBuilder.Entity("Kiosk.Domain.Auditoria.AuditoriaEvento", b =>
                {
                    b.HasOne("Kiosk.Domain.Comercios.Comercio", null)
                        .WithMany()
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiosk.Domain.Catalogos.Categoria", b =>
                {
                    b.HasOne("Kiosk.Domain.Comercios.Comercio", null)
                        .WithMany()
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiosk.Domain.Catalogos.Presentacion", b =>
                {
                    b.HasOne("Kiosk.Domain.Catalogos.Producto", null)
                        .WithMany("Presentaciones")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiosk.Domain.Catalogos.Producto", b =>
                {
                    b.HasOne("Kiosk.Domain.Catalogos.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("Kiosk.Domain.Comercios.Comercio", null)
                        .WithMany()
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiosk.Domain.Configuracion.Configuracion", b =>
                {
                    b.HasOne("Kiosk.Domain.Comercios.Comercio", null)
                        .WithMany()
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiosk.Domain.Stock.MovimientoStock", b =>
                {
                    b.HasOne("Kiosk.Domain.Catalogos.Presentacion", null)
                        .WithMany()
                        .HasForeignKey("PresentacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosk.Domain.Ventas.Venta", null)
                        .WithMany()
                        .HasForeignKey("VentaId");
                });

            modelBuilder.Entity("Kiosk.Domain.Usuarios.Usuario", b =>
                {
                    b.HasOne("Kiosk.Domain.Comercios.Comercio", null)
                        .WithMany()
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiosk.Domain.Ventas.Caja", b =>
                {
                    b.HasOne("Kiosk.Domain.Comercios.Comercio", null)
                        .WithMany()
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosk.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiosk.Domain.Ventas.LineaVenta", b =>
                {
                    b.HasOne("Kiosk.Domain.Catalogos.Presentacion", null)
                        .WithMany()
                        .HasForeignKey("PresentacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosk.Domain.Ventas.Venta", null)
                        .WithMany("Lineas")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiosk.Domain.Ventas.Pago", b =>
                {
                    b.HasOne("Kiosk.Domain.Ventas.Venta", null)
                        .WithMany("Pagos")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiosk.Domain.Ventas.Venta", b =>
                {
                    b.HasOne("Kiosk.Domain.Ventas.Caja", null)
                        .WithMany()
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiosk.Domain.Comercios.Comercio", null)
                        .WithMany()
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiosk.Domain.Whatsapp.Intencion", b =>
                {
                    b.HasOne("Kiosk.Domain.Comercios.Comercio", null)
                        .WithMany()
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiosk.Domain.Whatsapp.WhatsappWhitelist", b =>
                {
                    b.HasOne("Kiosk.Domain.Comercios.Comercio", null)
                        .WithMany()
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiosk.Domain.Catalogos.Producto", b =>
                {
                    b.Navigation("Presentaciones");
                });

            modelBuilder.Entity("Kiosk.Domain.Ventas.Venta", b =>
                {
                    b.Navigation("Lineas");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
